//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardAutoTesting.Service {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.tCheckDataTestAteSoap")]
    public interface tCheckDataTestAteSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckEmp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckEmp(string EMP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckEmp_NEW", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckEmp_NEW(string EMP, string ipaddress, string macaddress, string mygroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllStation(string woId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStationXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAllStationXML(string woId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWOCraftInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetWOCraftInfo(string woId, string Flag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCraftInfoByRouteId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetCraftInfoByRouteId(string RouteId, string Flag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Check_Route_ATE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Check_Route_ATE(string DATA, string Route, string WO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INS_ATE_Back", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string INS_ATE_Back(string DATA, string Route, string EMP, string LINE);
        
        // CODEGEN: 消息 ATE_Call_Back_First 的包装名称(ATE_Call_Back_First)以后生成的消息协定与默认值(PRO_INS_ATE_BACK)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ATE_Call_Back_First", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BoardAutoTesting.Service.ATE_Call_Back_First1 PRO_INS_ATE_BACK(BoardAutoTesting.Service.ATE_Call_Back_First request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLineList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLineList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLineListXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetLineListXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Line_List", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Get_Line_List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWOSnRule", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetWOSnRule(string woId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWOSnRuleXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetWOSnRuleXML(string woId);
        
        // CODEGEN: 消息 Sn_Rule_XML 的包装名称(Sn_Rule_XML)以后生成的消息协定与默认值(Get_WO_SnRule)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sn_Rule_XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BoardAutoTesting.Service.Sn_Rule_XML1 Get_WO_SnRule(BoardAutoTesting.Service.Sn_Rule_XML request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertWipKeyParts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertWipKeyParts(BoardAutoTesting.Service.tWipKeyPartTable[] lswipkeypart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEsnDataInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetEsnDataInfo(string sntype, string snval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEsnDataInfoXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetEsnDataInfoXML(string sntype, string snval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEsnDataInfoXMLBySntype", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetEsnDataInfoXMLBySntype(string sntype, string snval, string[] arrSntype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEsnDataInfoBySntype", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetEsnDataInfoBySntype(string sntype, string snval, string[] arrSntype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSnInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSnInfo(string serial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSnInfoXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSnInfoXML(string serial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSnWipKeyPartsData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSnWipKeyPartsData(string SN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSnWipKeyPartsDataXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSnWipKeyPartsDataXML(string SN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWoList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetWoList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetATEScripts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetATEScripts(string woid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAteScriptsStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAteScriptsStr(string woId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAteScriptsXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAteScriptsXML(string woId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteLogOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeleteLogOut(string userId, string strIpaddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCartonPrintContent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCartonPrintContent(string cartonId, string[] Content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SP_TEST_INPUT_ALL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SP_TEST_INPUT_ALL(string DATA, string LINE, string MYGROUP, string WOID, string EMPNO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChkUserAteEmp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ChkUserAteEmp(string UserId, string CraftId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetErrorCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetErrorCode(string ec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetErrorCodeXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetErrorCodeXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SP_PRO_SN_INPUT_MOBILE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SP_PRO_SN_INPUT_MOBILE(string DATA, string MYGROUP, string LINE, string WO, string EMP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWoInfoByWo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetWoInfoByWo(string woId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWoInfoByWoXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetWoInfoByWoXml(string woId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductByPartNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetProductByPartNumber(string PartNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductLableNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetProductLableNames(string partnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSnMacImeiForAte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetSnMacImeiForAte(string Esn, string sntype, string woId, int snqty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_T_TESTRESULT_INFO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Insert_T_TESTRESULT_INFO(BoardAutoTesting.Service.tT_TESTRESULT_INFO tti);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWoVersionInfoXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetWoVersionInfoXML(string woid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPnMarkBitInfoXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPnMarkBitInfoXML(string pn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWoVersionInfoDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetWoVersionInfoDataSet(string woid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPnMarkBitInfoDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPnMarkBitInfoDataSet(string pn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CHECK_ROUTE_TOOLS_ATE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CHECK_ROUTE_TOOLS_ATE(string DATA, string MYGROUP, string WO, string Tools);
        
        // CODEGEN: 消息 GetRouteInfo 的包装名称(GetRouteInfo)以后生成的消息协定与默认值(Get_Route_Info)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRouteInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BoardAutoTesting.Service.GetRouteInfo1 Get_Route_Info(BoardAutoTesting.Service.GetRouteInfo request);
        
        // CODEGEN: 消息 CheckLineEmployee 的包装名称(CheckLineEmployee)以后生成的消息协定与默认值(CHECK_SET_LINE_EMPLOYEE)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckLineEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BoardAutoTesting.Service.CheckLineEmployee1 CHECK_SET_LINE_EMPLOYEE(BoardAutoTesting.Service.CheckLineEmployee request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPDATE_WIP_TRACKING", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UPDATE_WIP_TRACKING(string Json);
        
        // CODEGEN: 消息 Get_WIP_TRACKING 的包装名称(Get_WIP_TRACKING)以后生成的消息协定与默认值(Get_WIP_TRACKING_XML)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_WIP_TRACKING", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BoardAutoTesting.Service.Get_WIP_TRACKING1 Get_WIP_TRACKING_XML(BoardAutoTesting.Service.Get_WIP_TRACKING request);
        
        // CODEGEN: 消息 Get_Station_Checkrules 的包装名称(Get_Station_Checkrules)以后生成的消息协定与默认值(Get_b_station_checkrules)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Station_Checkrules", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BoardAutoTesting.Service.Get_Station_Checkrules1 Get_b_station_checkrules(BoardAutoTesting.Service.Get_Station_Checkrules request);
        
        // CODEGEN: 消息 GetStnRec 的包装名称(GetStnRec)以后生成的消息协定与默认值(Get_Stn_Rec)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStnRec", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BoardAutoTesting.Service.GetStnRec1 Get_Stn_Rec(BoardAutoTesting.Service.GetStnRec request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteProcedure", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ExecuteProcedure(string Storedproc, string Json);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ATE_Call_Back_First", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ATE_Call_Back_First {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DATA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string MYGROUP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string SECTION_NAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string STATION_NAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string EMP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string LINE;
        
        public ATE_Call_Back_First() {
        }
        
        public ATE_Call_Back_First(string DATA, string MYGROUP, string SECTION_NAME, string STATION_NAME, string EMP, string LINE) {
            this.DATA = DATA;
            this.MYGROUP = MYGROUP;
            this.SECTION_NAME = SECTION_NAME;
            this.STATION_NAME = STATION_NAME;
            this.EMP = EMP;
            this.LINE = LINE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ATE_Call_Back_FirstResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ATE_Call_Back_First1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ATE_Call_Back_FirstResult;
        
        public ATE_Call_Back_First1() {
        }
        
        public ATE_Call_Back_First1(string ATE_Call_Back_FirstResult) {
            this.ATE_Call_Back_FirstResult = ATE_Call_Back_FirstResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sn_Rule_XML", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Sn_Rule_XML {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string woId;
        
        public Sn_Rule_XML() {
        }
        
        public Sn_Rule_XML(string woId) {
            this.woId = woId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sn_Rule_XMLResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Sn_Rule_XML1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Sn_Rule_XMLResult;
        
        public Sn_Rule_XML1() {
        }
        
        public Sn_Rule_XML1(string Sn_Rule_XMLResult) {
            this.Sn_Rule_XMLResult = Sn_Rule_XMLResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tWipKeyPartTable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idxField;
        
        private string esnField;
        
        private string woIdField;
        
        private string sntypeField;
        
        private string snvalField;
        
        private string stationField;
        
        private string kPNOField;
        
        private string recdateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idx {
            get {
                return this.idxField;
            }
            set {
                this.idxField = value;
                this.RaisePropertyChanged("idx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string esn {
            get {
                return this.esnField;
            }
            set {
                this.esnField = value;
                this.RaisePropertyChanged("esn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string woId {
            get {
                return this.woIdField;
            }
            set {
                this.woIdField = value;
                this.RaisePropertyChanged("woId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sntype {
            get {
                return this.sntypeField;
            }
            set {
                this.sntypeField = value;
                this.RaisePropertyChanged("sntype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string snval {
            get {
                return this.snvalField;
            }
            set {
                this.snvalField = value;
                this.RaisePropertyChanged("snval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string station {
            get {
                return this.stationField;
            }
            set {
                this.stationField = value;
                this.RaisePropertyChanged("station");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string KPNO {
            get {
                return this.kPNOField;
            }
            set {
                this.kPNOField = value;
                this.RaisePropertyChanged("KPNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string recdate {
            get {
                return this.recdateField;
            }
            set {
                this.recdateField = value;
                this.RaisePropertyChanged("recdate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tT_TESTRESULT_INFO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eSNField;
        
        private string wOIDField;
        
        private string tESTSTATIONField;
        
        private string tESTRESULTField;
        
        private string eQPIDField;
        
        private string eQPTYPEField;
        
        private string cUSERField;
        
        private string fAILDESCField;
        
        private string pARTNUMBERField;
        
        private string pRODUCTNAMEField;
        
        private string repairFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ESN {
            get {
                return this.eSNField;
            }
            set {
                this.eSNField = value;
                this.RaisePropertyChanged("ESN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string WOID {
            get {
                return this.wOIDField;
            }
            set {
                this.wOIDField = value;
                this.RaisePropertyChanged("WOID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TESTSTATION {
            get {
                return this.tESTSTATIONField;
            }
            set {
                this.tESTSTATIONField = value;
                this.RaisePropertyChanged("TESTSTATION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TESTRESULT {
            get {
                return this.tESTRESULTField;
            }
            set {
                this.tESTRESULTField = value;
                this.RaisePropertyChanged("TESTRESULT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string EQPID {
            get {
                return this.eQPIDField;
            }
            set {
                this.eQPIDField = value;
                this.RaisePropertyChanged("EQPID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string EQPTYPE {
            get {
                return this.eQPTYPEField;
            }
            set {
                this.eQPTYPEField = value;
                this.RaisePropertyChanged("EQPTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CUSER {
            get {
                return this.cUSERField;
            }
            set {
                this.cUSERField = value;
                this.RaisePropertyChanged("CUSER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FAILDESC {
            get {
                return this.fAILDESCField;
            }
            set {
                this.fAILDESCField = value;
                this.RaisePropertyChanged("FAILDESC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PARTNUMBER {
            get {
                return this.pARTNUMBERField;
            }
            set {
                this.pARTNUMBERField = value;
                this.RaisePropertyChanged("PARTNUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PRODUCTNAME {
            get {
                return this.pRODUCTNAMEField;
            }
            set {
                this.pRODUCTNAMEField = value;
                this.RaisePropertyChanged("PRODUCTNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string RepairFlag {
            get {
                return this.repairFlagField;
            }
            set {
                this.repairFlagField = value;
                this.RaisePropertyChanged("RepairFlag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRouteInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRouteInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SECTION_NAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string CRAFTNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string TEST_FLAG;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string CHECK_TOOLS_FLAG;
        
        public GetRouteInfo() {
        }
        
        public GetRouteInfo(string SECTION_NAME, string CRAFTNAME, string TEST_FLAG, string CHECK_TOOLS_FLAG) {
            this.SECTION_NAME = SECTION_NAME;
            this.CRAFTNAME = CRAFTNAME;
            this.TEST_FLAG = TEST_FLAG;
            this.CHECK_TOOLS_FLAG = CHECK_TOOLS_FLAG;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRouteInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRouteInfo1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetRouteInfoResult;
        
        public GetRouteInfo1() {
        }
        
        public GetRouteInfo1(string GetRouteInfoResult) {
            this.GetRouteInfoResult = GetRouteInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckLineEmployee", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckLineEmployee {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string PWD;
        
        public CheckLineEmployee() {
        }
        
        public CheckLineEmployee(string UserId, string PWD) {
            this.UserId = UserId;
            this.PWD = PWD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckLineEmployeeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckLineEmployee1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CheckLineEmployeeResult;
        
        public CheckLineEmployee1() {
        }
        
        public CheckLineEmployee1(string CheckLineEmployeeResult) {
            this.CheckLineEmployeeResult = CheckLineEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Get_WIP_TRACKING", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Get_WIP_TRACKING {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Esn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Fields;
        
        public Get_WIP_TRACKING() {
        }
        
        public Get_WIP_TRACKING(string Esn, string Fields) {
            this.Esn = Esn;
            this.Fields = Fields;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Get_WIP_TRACKINGResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Get_WIP_TRACKING1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Get_WIP_TRACKINGResult;
        
        public Get_WIP_TRACKING1() {
        }
        
        public Get_WIP_TRACKING1(string Get_WIP_TRACKINGResult) {
            this.Get_WIP_TRACKINGResult = Get_WIP_TRACKINGResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Get_Station_Checkrules", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Get_Station_Checkrules {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Json;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Fileds;
        
        public Get_Station_Checkrules() {
        }
        
        public Get_Station_Checkrules(string Json, string Fileds) {
            this.Json = Json;
            this.Fileds = Fileds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Get_Station_CheckrulesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Get_Station_Checkrules1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Get_Station_CheckrulesResult;
        
        public Get_Station_Checkrules1() {
        }
        
        public Get_Station_Checkrules1(string Get_Station_CheckrulesResult) {
            this.Get_Station_CheckrulesResult = Get_Station_CheckrulesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStnRec", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStnRec {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Json;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Fields;
        
        public GetStnRec() {
        }
        
        public GetStnRec(string Json, string Fields) {
            this.Json = Json;
            this.Fields = Fields;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStnRecResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStnRec1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetStnRecResult;
        
        public GetStnRec1() {
        }
        
        public GetStnRec1(string GetStnRecResult) {
            this.GetStnRecResult = GetStnRecResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface tCheckDataTestAteSoapChannel : BoardAutoTesting.Service.tCheckDataTestAteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class tCheckDataTestAteSoapClient : System.ServiceModel.ClientBase<BoardAutoTesting.Service.tCheckDataTestAteSoap>, BoardAutoTesting.Service.tCheckDataTestAteSoap {
        
        public tCheckDataTestAteSoapClient() {
        }
        
        public tCheckDataTestAteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public tCheckDataTestAteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public tCheckDataTestAteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public tCheckDataTestAteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckEmp(string EMP) {
            return base.Channel.CheckEmp(EMP);
        }
        
        public string CheckEmp_NEW(string EMP, string ipaddress, string macaddress, string mygroup) {
            return base.Channel.CheckEmp_NEW(EMP, ipaddress, macaddress, mygroup);
        }
        
        public System.Data.DataSet GetAllStation(string woId) {
            return base.Channel.GetAllStation(woId);
        }
        
        public string GetAllStationXML(string woId) {
            return base.Channel.GetAllStationXML(woId);
        }
        
        public string[] GetWOCraftInfo(string woId, string Flag) {
            return base.Channel.GetWOCraftInfo(woId, Flag);
        }
        
        public string[] GetCraftInfoByRouteId(string RouteId, string Flag) {
            return base.Channel.GetCraftInfoByRouteId(RouteId, Flag);
        }
        
        public string Check_Route_ATE(string DATA, string Route, string WO) {
            return base.Channel.Check_Route_ATE(DATA, Route, WO);
        }
        
        public string INS_ATE_Back(string DATA, string Route, string EMP, string LINE) {
            return base.Channel.INS_ATE_Back(DATA, Route, EMP, LINE);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoardAutoTesting.Service.ATE_Call_Back_First1 BoardAutoTesting.Service.tCheckDataTestAteSoap.PRO_INS_ATE_BACK(BoardAutoTesting.Service.ATE_Call_Back_First request) {
            return base.Channel.PRO_INS_ATE_BACK(request);
        }
        
        public string PRO_INS_ATE_BACK(string DATA, string MYGROUP, string SECTION_NAME, string STATION_NAME, string EMP, string LINE) {
            BoardAutoTesting.Service.ATE_Call_Back_First inValue = new BoardAutoTesting.Service.ATE_Call_Back_First();
            inValue.DATA = DATA;
            inValue.MYGROUP = MYGROUP;
            inValue.SECTION_NAME = SECTION_NAME;
            inValue.STATION_NAME = STATION_NAME;
            inValue.EMP = EMP;
            inValue.LINE = LINE;
            BoardAutoTesting.Service.ATE_Call_Back_First1 retVal = ((BoardAutoTesting.Service.tCheckDataTestAteSoap)(this)).PRO_INS_ATE_BACK(inValue);
            return retVal.ATE_Call_Back_FirstResult;
        }
        
        public System.Data.DataSet GetLineList() {
            return base.Channel.GetLineList();
        }
        
        public string GetLineListXML() {
            return base.Channel.GetLineListXML();
        }
        
        public string[] Get_Line_List() {
            return base.Channel.Get_Line_List();
        }
        
        public System.Data.DataSet GetWOSnRule(string woId) {
            return base.Channel.GetWOSnRule(woId);
        }
        
        public string GetWOSnRuleXML(string woId) {
            return base.Channel.GetWOSnRuleXML(woId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoardAutoTesting.Service.Sn_Rule_XML1 BoardAutoTesting.Service.tCheckDataTestAteSoap.Get_WO_SnRule(BoardAutoTesting.Service.Sn_Rule_XML request) {
            return base.Channel.Get_WO_SnRule(request);
        }
        
        public string Get_WO_SnRule(string woId) {
            BoardAutoTesting.Service.Sn_Rule_XML inValue = new BoardAutoTesting.Service.Sn_Rule_XML();
            inValue.woId = woId;
            BoardAutoTesting.Service.Sn_Rule_XML1 retVal = ((BoardAutoTesting.Service.tCheckDataTestAteSoap)(this)).Get_WO_SnRule(inValue);
            return retVal.Sn_Rule_XMLResult;
        }
        
        public string InsertWipKeyParts(BoardAutoTesting.Service.tWipKeyPartTable[] lswipkeypart) {
            return base.Channel.InsertWipKeyParts(lswipkeypart);
        }
        
        public System.Data.DataSet GetEsnDataInfo(string sntype, string snval) {
            return base.Channel.GetEsnDataInfo(sntype, snval);
        }
        
        public string GetEsnDataInfoXML(string sntype, string snval) {
            return base.Channel.GetEsnDataInfoXML(sntype, snval);
        }
        
        public string GetEsnDataInfoXMLBySntype(string sntype, string snval, string[] arrSntype) {
            return base.Channel.GetEsnDataInfoXMLBySntype(sntype, snval, arrSntype);
        }
        
        public System.Data.DataSet GetEsnDataInfoBySntype(string sntype, string snval, string[] arrSntype) {
            return base.Channel.GetEsnDataInfoBySntype(sntype, snval, arrSntype);
        }
        
        public System.Data.DataSet GetSnInfo(string serial) {
            return base.Channel.GetSnInfo(serial);
        }
        
        public string GetSnInfoXML(string serial) {
            return base.Channel.GetSnInfoXML(serial);
        }
        
        public System.Data.DataSet GetSnWipKeyPartsData(string SN) {
            return base.Channel.GetSnWipKeyPartsData(SN);
        }
        
        public string GetSnWipKeyPartsDataXML(string SN) {
            return base.Channel.GetSnWipKeyPartsDataXML(SN);
        }
        
        public string[] GetWoList() {
            return base.Channel.GetWoList();
        }
        
        public System.Data.DataSet GetATEScripts(string woid) {
            return base.Channel.GetATEScripts(woid);
        }
        
        public string GetAteScriptsStr(string woId) {
            return base.Channel.GetAteScriptsStr(woId);
        }
        
        public string GetAteScriptsXML(string woId) {
            return base.Channel.GetAteScriptsXML(woId);
        }
        
        public string DeleteLogOut(string userId, string strIpaddress) {
            return base.Channel.DeleteLogOut(userId, strIpaddress);
        }
        
        public System.Data.DataSet GetCartonPrintContent(string cartonId, string[] Content) {
            return base.Channel.GetCartonPrintContent(cartonId, Content);
        }
        
        public string SP_TEST_INPUT_ALL(string DATA, string LINE, string MYGROUP, string WOID, string EMPNO) {
            return base.Channel.SP_TEST_INPUT_ALL(DATA, LINE, MYGROUP, WOID, EMPNO);
        }
        
        public string ChkUserAteEmp(string UserId, string CraftId) {
            return base.Channel.ChkUserAteEmp(UserId, CraftId);
        }
        
        public string GetErrorCode(string ec) {
            return base.Channel.GetErrorCode(ec);
        }
        
        public string GetErrorCodeXML() {
            return base.Channel.GetErrorCodeXML();
        }
        
        public string SP_PRO_SN_INPUT_MOBILE(string DATA, string MYGROUP, string LINE, string WO, string EMP) {
            return base.Channel.SP_PRO_SN_INPUT_MOBILE(DATA, MYGROUP, LINE, WO, EMP);
        }
        
        public System.Data.DataSet GetWoInfoByWo(string woId) {
            return base.Channel.GetWoInfoByWo(woId);
        }
        
        public string GetWoInfoByWoXml(string woId) {
            return base.Channel.GetWoInfoByWoXml(woId);
        }
        
        public System.Data.DataSet GetProductByPartNumber(string PartNumber) {
            return base.Channel.GetProductByPartNumber(PartNumber);
        }
        
        public string[] GetProductLableNames(string partnumber) {
            return base.Channel.GetProductLableNames(partnumber);
        }
        
        public string[] GetSnMacImeiForAte(string Esn, string sntype, string woId, int snqty) {
            return base.Channel.GetSnMacImeiForAte(Esn, sntype, woId, snqty);
        }
        
        public string Insert_T_TESTRESULT_INFO(BoardAutoTesting.Service.tT_TESTRESULT_INFO tti) {
            return base.Channel.Insert_T_TESTRESULT_INFO(tti);
        }
        
        public string GetWoVersionInfoXML(string woid) {
            return base.Channel.GetWoVersionInfoXML(woid);
        }
        
        public string GetPnMarkBitInfoXML(string pn) {
            return base.Channel.GetPnMarkBitInfoXML(pn);
        }
        
        public System.Data.DataSet GetWoVersionInfoDataSet(string woid) {
            return base.Channel.GetWoVersionInfoDataSet(woid);
        }
        
        public System.Data.DataSet GetPnMarkBitInfoDataSet(string pn) {
            return base.Channel.GetPnMarkBitInfoDataSet(pn);
        }
        
        public string CHECK_ROUTE_TOOLS_ATE(string DATA, string MYGROUP, string WO, string Tools) {
            return base.Channel.CHECK_ROUTE_TOOLS_ATE(DATA, MYGROUP, WO, Tools);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoardAutoTesting.Service.GetRouteInfo1 BoardAutoTesting.Service.tCheckDataTestAteSoap.Get_Route_Info(BoardAutoTesting.Service.GetRouteInfo request) {
            return base.Channel.Get_Route_Info(request);
        }
        
        public string Get_Route_Info(string SECTION_NAME, string CRAFTNAME, string TEST_FLAG, string CHECK_TOOLS_FLAG) {
            BoardAutoTesting.Service.GetRouteInfo inValue = new BoardAutoTesting.Service.GetRouteInfo();
            inValue.SECTION_NAME = SECTION_NAME;
            inValue.CRAFTNAME = CRAFTNAME;
            inValue.TEST_FLAG = TEST_FLAG;
            inValue.CHECK_TOOLS_FLAG = CHECK_TOOLS_FLAG;
            BoardAutoTesting.Service.GetRouteInfo1 retVal = ((BoardAutoTesting.Service.tCheckDataTestAteSoap)(this)).Get_Route_Info(inValue);
            return retVal.GetRouteInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoardAutoTesting.Service.CheckLineEmployee1 BoardAutoTesting.Service.tCheckDataTestAteSoap.CHECK_SET_LINE_EMPLOYEE(BoardAutoTesting.Service.CheckLineEmployee request) {
            return base.Channel.CHECK_SET_LINE_EMPLOYEE(request);
        }
        
        public string CHECK_SET_LINE_EMPLOYEE(string UserId, string PWD) {
            BoardAutoTesting.Service.CheckLineEmployee inValue = new BoardAutoTesting.Service.CheckLineEmployee();
            inValue.UserId = UserId;
            inValue.PWD = PWD;
            BoardAutoTesting.Service.CheckLineEmployee1 retVal = ((BoardAutoTesting.Service.tCheckDataTestAteSoap)(this)).CHECK_SET_LINE_EMPLOYEE(inValue);
            return retVal.CheckLineEmployeeResult;
        }
        
        public string UPDATE_WIP_TRACKING(string Json) {
            return base.Channel.UPDATE_WIP_TRACKING(Json);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoardAutoTesting.Service.Get_WIP_TRACKING1 BoardAutoTesting.Service.tCheckDataTestAteSoap.Get_WIP_TRACKING_XML(BoardAutoTesting.Service.Get_WIP_TRACKING request) {
            return base.Channel.Get_WIP_TRACKING_XML(request);
        }
        
        public string Get_WIP_TRACKING_XML(string Esn, string Fields) {
            BoardAutoTesting.Service.Get_WIP_TRACKING inValue = new BoardAutoTesting.Service.Get_WIP_TRACKING();
            inValue.Esn = Esn;
            inValue.Fields = Fields;
            BoardAutoTesting.Service.Get_WIP_TRACKING1 retVal = ((BoardAutoTesting.Service.tCheckDataTestAteSoap)(this)).Get_WIP_TRACKING_XML(inValue);
            return retVal.Get_WIP_TRACKINGResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoardAutoTesting.Service.Get_Station_Checkrules1 BoardAutoTesting.Service.tCheckDataTestAteSoap.Get_b_station_checkrules(BoardAutoTesting.Service.Get_Station_Checkrules request) {
            return base.Channel.Get_b_station_checkrules(request);
        }
        
        public string Get_b_station_checkrules(string Json, string Fileds) {
            BoardAutoTesting.Service.Get_Station_Checkrules inValue = new BoardAutoTesting.Service.Get_Station_Checkrules();
            inValue.Json = Json;
            inValue.Fileds = Fileds;
            BoardAutoTesting.Service.Get_Station_Checkrules1 retVal = ((BoardAutoTesting.Service.tCheckDataTestAteSoap)(this)).Get_b_station_checkrules(inValue);
            return retVal.Get_Station_CheckrulesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoardAutoTesting.Service.GetStnRec1 BoardAutoTesting.Service.tCheckDataTestAteSoap.Get_Stn_Rec(BoardAutoTesting.Service.GetStnRec request) {
            return base.Channel.Get_Stn_Rec(request);
        }
        
        public string Get_Stn_Rec(string Json, string Fields) {
            BoardAutoTesting.Service.GetStnRec inValue = new BoardAutoTesting.Service.GetStnRec();
            inValue.Json = Json;
            inValue.Fields = Fields;
            BoardAutoTesting.Service.GetStnRec1 retVal = ((BoardAutoTesting.Service.tCheckDataTestAteSoap)(this)).Get_Stn_Rec(inValue);
            return retVal.GetStnRecResult;
        }
        
        public string ExecuteProcedure(string Storedproc, string Json) {
            return base.Channel.ExecuteProcedure(Storedproc, Json);
        }
    }
}
