//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardAutoTesting.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoardAutoTesting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 指令执行完成 的本地化字符串。
        /// </summary>
        internal static string CommandExecuted {
            get {
                return ResourceManager.GetString("CommandExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置错误 的本地化字符串。
        /// </summary>
        internal static string ConfigError {
            get {
                return ResourceManager.GetString("ConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接 的本地化字符串。
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断开 的本地化字符串。
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后一站更新完成 的本地化字符串。
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Craft00001 的本地化字符串。
        /// </summary>
        internal static string InitCraft {
            get {
                return ResourceManager.GetString("InitCraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效IP 的本地化字符串。
        /// </summary>
        internal static string InvalidIp {
            get {
                return ResourceManager.GetString("InvalidIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP或端口不能为空！ 的本地化字符串。
        /// </summary>
        internal static string IpPortError {
            get {
                return ResourceManager.GetString("IpPortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口不存在 的本地化字符串。
        /// </summary>
        internal static string NoPort {
            get {
                return ResourceManager.GetString("NoPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应答超时 的本地化字符串。
        /// </summary>
        internal static string NoResponse {
            get {
                return ResourceManager.GetString("NoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有测试中的产品 的本地化字符串。
        /// </summary>
        internal static string NoTestingProduct {
            get {
                return ResourceManager.GetString("NoTestingProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7600 的本地化字符串。
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前机台不存在任何串口，请连接串口！ 的本地化字符串。
        /// </summary>
        internal static string PromoteNoPort {
            get {
                return ResourceManager.GetString("PromoteNoPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动服务器 的本地化字符串。
        /// </summary>
        internal static string StartServer {
            get {
                return ResourceManager.GetString("StartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止服务器 的本地化字符串。
        /// </summary>
        internal static string StopServer {
            get {
                return ResourceManager.GetString("StopServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定关闭服务器？ 的本地化字符串。
        /// </summary>
        internal static string SureToExit {
            get {
                return ResourceManager.GetString("SureToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统提示 的本地化字符串。
        /// </summary>
        internal static string SystemPromote {
            get {
                return ResourceManager.GetString("SystemPromote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机台未配置 的本地化字符串。
        /// </summary>
        internal static string UnconfigedCraft {
            get {
                return ResourceManager.GetString("UnconfigedCraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新数据超时 的本地化字符串。
        /// </summary>
        internal static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指令错误 的本地化字符串。
        /// </summary>
        internal static string WrongCommand {
            get {
                return ResourceManager.GetString("WrongCommand", resourceCulture);
            }
        }
    }
}
